version: '3'

services:

  master:
    image: mysql:5.5.40
    container_name: master
    hostname: master
    ports:
      - '3304:3306'
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - ./master/my-cnf:/etc/mysql/my.cnf
      - ./master/entrypoint.sh:/entrypoint.sh

  slave:
    image: mysql:5.5.40
    container_name: slave
    hostname: slave
    ports:
      - '3305:3306'
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - ./slave/my-cnf:/etc/mysql/my.cnf
      - ./slave/entrypoint.sh:/entrypoint.sh
